/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author asus
 */
public class Bienvenido extends javax.swing.JFrame {

    private int auxiliar = 0;
    private boolean hecho = false;
    hilo ejecutar = new hilo();

    /**
     * Creates new form Bienvenido
     */
    public Bienvenido() {
        initComponents();
        Bienvenido.this.getRootPane().setOpaque(false);
        Bienvenido.this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        Bienvenido.this.setBackground(new Color(0, 0, 0, 0));
        this.setResizable(false);//La pantalla aparecera en el centro
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Logo.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        Barra = new javax.swing.JProgressBar();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setIconImage(getIconImage());
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setText("jLabel2");
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 30));
        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 330, 30));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen de bienvenidos.png"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (hecho == false) {
            hecho = true;
            Barra.setMaximum(50);//Para calcular el progreso de la barra
            Barra.setMinimum(0);
            Barra.setStringPainted(true);//Muestra el avance de la barra
            ejecutar.start();//Ejecuta el hilo creado
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    private class hilo extends Thread {

        @Override
        public void run() {
            try {
                while (true) { //Siempre va a estar en ejecucion
                    auxiliar++;//Va a aumentar cada vez que se ejecute
                    Barra.setValue(auxiliar);//El valor que le va a mandar a toda la barra
                    repaint();//noten los cambios
                    switch (auxiliar) {
                        case 3: //Estos mensjaes solo los que salgran hasta que termine de contar las milesimas
                            text.setText("Procesando programa...");
                            break;
                        case 20:
                            text.setText("Leyendo datos");
                            break;
                        case 50:
                            text.setText("Carga completa");
                            break;
                        case 60:
                            Idiomas objeto = new Idiomas();//Clase elegida para ser la siguiente
                            objeto.setVisible(true);
                            objeto.setLocationRelativeTo(Bienvenido.this);//Ya que estamos dentro del hilo creado
                            Bienvenido.this.dispose();
                            break;
                    }
                    Thread.sleep(100);
                } //Esto hace que el programa se ejecute milesimas por segundo
            } catch (InterruptedException ex) {
                Logger.getLogger(Bienvenido.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Barra;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
